export const STORAGE_KEYS = Object.freeze({
  legacyMasterPassword: 'my_master_password',
  masterPasswordVerifier: 'my_master_password_verifier_v1',
  masterPasswordBiometricBinding: 'my_master_password_biometric_binding_v1',
  customBackground: 'my_custom_bg',
  themeSettings: 'my_theme_settings',
  bannerSettings: 'my_banner_settings',
  legacyAiSettings: 'my_ai_settings',
  aiProviderSettings: 'my_ai_provider_settings_v1',
  securitySettings: 'my_security_settings',
  notificationSettings: 'my_notification_settings',
  notificationAiContent: 'my_notification_ai_content',
  healthSettings: 'my_health_settings',
  homeCache: 'my_home_cache',
  debtRecords: 'my_debt_manager_data',
  weightRecords: 'my_weight_records_data',
  moodRecords: 'my_mood_records_data',
  moodTrackingStartDate: 'my_mood_tracking_start_date',
  moodCustomTags: 'my_mood_custom_tags',
  moodDefinitions: 'my_mood_definitions_v1',
  passwordVault: 'my_password_vault_encrypted',
  passwordVaultCategories: 'my_password_vault_categories_encrypted',
  legacyPasswordVault: 'my_password_manager_data',
  scheduleData: 'my_schedule_data_v2',
  homeWidgetSnapshot: 'my_home_widget_snapshot_v1',
  scheduleWidgetSnapshot: 'my_schedule_widget_snapshot'
})
